package eu.esic.formation.initspring.springdao.entity;

// Generated 11 avr. 2016 08:10:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * Alerte generated by hbm2java
 */
public class Alerte implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3411797828568263897L;
	private Integer idAlerte;
	private String villeDepart;
	private String villeArrivee;
	private Date dateDepot;
	private Utilisateur user;

	public Alerte() {
	}

	public Alerte(Date dateDepot) {
		this.dateDepot = dateDepot;
	}

	public Alerte(String villeDepart, String villeArrivee,Utilisateur u) {
		this.villeDepart = villeDepart;
		this.villeArrivee = villeArrivee;
		this.dateDepot = new Date();
		this.user = u;
	}

	public Integer getIdAlerte() {
		return this.idAlerte;
	}

	public void setIdAlerte(Integer idAlerte) {
		this.idAlerte = idAlerte;
	}

	public String getVilleDepart() {
		return this.villeDepart;
	}

	public void setVilleDepart(String villeDepart) {
		this.villeDepart = villeDepart;
	}

	public String getVilleArrivee() {
		return this.villeArrivee;
	}

	public void setVilleArrivee(String villeArrivee) {
		this.villeArrivee = villeArrivee;
	}

	public Date getDateDepot() {
		return this.dateDepot;
	}

	public void setDateDepot(Date dateDepot) {
		this.dateDepot = dateDepot;
	}

	public Utilisateur getUser() {
		return user;
	}

	public void setUser(Utilisateur user) {
		this.user = user;
	}
	
	public String toString(){
		return ToStringBuilder.reflectionToString(this); 
	}

}
