package eu.esic.formation.initspring.springdao.entity;

// Generated 11 avr. 2016 08:10:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7204091048301404475L;
	private Integer idComment;
	private String corps;
	private Date dateCreation;
	private Utilisateur user;
	
	public Comment() {
	}


	public Comment(String corps) {
		this.corps = corps;
		this.dateCreation = new Date();
	}

	public Integer getIdComment() {
		return this.idComment;
	}

	public void setIdComment(Integer idComment) {
		this.idComment = idComment;
	}

	public String getCorps() {
		return this.corps;
	}

	public void setCorps(String corps) {
		this.corps = corps;
	}

	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}


	public Utilisateur getUser() {
		return user;
	}


	public void setUser(Utilisateur user) {
		this.user = user;
	}
	
	public String toString(){
		return ToStringBuilder.reflectionToString(this); 
	}

}
