package eu.esic.formation.initspring.springdao.entity;

// Generated 11 avr. 2016 08:10:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * Image generated by hbm2java
 */
public class Image implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5748910683578473493L;
	private Integer idImage;
	private String chemin;
	private Date dateCreation;
	private Utilisateur user;

	public Image() {
	}


	public Image(String chemin,Utilisateur u) {
		this.chemin = chemin;
		this.user = u;
		this.dateCreation = new Date();
	}

	public Integer getIdImage() {
		return this.idImage;
	}

	public void setIdImage(Integer idImage) {
		this.idImage = idImage;
	}

	public String getChemin() {
		return this.chemin;
	}

	public void setChemin(String chemin) {
		this.chemin = chemin;
	}

	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	public Utilisateur getUser() {
		return user;
	}

	public void setUser(Utilisateur user) {
		this.user = user;
	}
	
	public String toString(){
		return ToStringBuilder.reflectionToString(this); 
	}

}
