package eu.esic.formation.initspring.springdao.entity;

// Generated 11 avr. 2016 08:10:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6176322215169828029L;
	private Integer idMessage;
	private String corps;
	private Date dateCreation;
	private Utilisateur user;
	private Annonce a;

	public Message() {
	}

	public Message(Annonce aP,Utilisateur uP) {
		this.a = aP;
		this.user = uP;
		this.dateCreation = new Date();
	}

	public Message(Utilisateur u, Annonce an, String corps) {
		this.user = u;
		this.a = an;
		this.corps = corps;
		this.dateCreation = new Date();
	}

	public Integer getIdMessage() {
		return this.idMessage;
	}

	public void setIdMessage(Integer idMessage) {
		this.idMessage = idMessage;
	}

	public String getCorps() {
		return this.corps;
	}

	public void setCorps(String corps) {
		this.corps = corps;
	}

	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	public Utilisateur getUser() {
		return user;
	}

	public void setUser(Utilisateur user) {
		this.user = user;
	}

	public Annonce getA() {
		return a;
	}

	public void setA(Annonce a) {
		this.a = a;
	}
	
	public String toString(){
		return ToStringBuilder.reflectionToString(this); 
	}

}
